export const ADD_PRODUCT = 'ADD_PRODUCT';
export const TOGGLE_SELECT_ALL = 'TOGGLE_SELECT_ALL';
export const TOGGLE_PRODUCT_SELECT = 'TOGGLE_PRODUCT_SELECT';
export const DELETE_SELECTED_PRODUCTS = 'DELETE_SELECTED_PRODUCTS';
